
// Comprehensive Indian stock list and search functionality
export interface StockInfo {
  symbol: string;
  name: string;
  exchange: string;
  sector?: string;
}

// Extended list of popular Indian stocks
const indianStocks: StockInfo[] = [
  // Nifty 50 stocks
  { symbol: 'RELIANCE.NS', name: 'Reliance Industries Limited', exchange: 'NSE', sector: 'Energy' },
  { symbol: 'TCS.NS', name: 'Tata Consultancy Services', exchange: 'NSE', sector: 'IT' },
  { symbol: 'HDFCBANK.NS', name: 'HDFC Bank Limited', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'INFY.NS', name: 'Infosys Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'ICICIBANK.NS', name: 'ICICI Bank Limited', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'KOTAKBANK.NS', name: 'Kotak Mahindra Bank', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'HINDUNILVR.NS', name: 'Hindustan Unilever Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'LT.NS', name: 'Larsen & Toubro Limited', exchange: 'NSE', sector: 'Infrastructure' },
  { symbol: 'SBIN.NS', name: 'State Bank of India', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'BHARTIARTL.NS', name: 'Bharti Airtel Limited', exchange: 'NSE', sector: 'Telecom' },
  { symbol: 'ITC.NS', name: 'ITC Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'ASIANPAINT.NS', name: 'Asian Paints Limited', exchange: 'NSE', sector: 'Paints' },
  { symbol: 'AXISBANK.NS', name: 'Axis Bank Limited', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'MARUTI.NS', name: 'Maruti Suzuki India Limited', exchange: 'NSE', sector: 'Auto' },
  { symbol: 'SUNPHARMA.NS', name: 'Sun Pharmaceutical Industries', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'ULTRACEMCO.NS', name: 'UltraTech Cement Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'TITAN.NS', name: 'Titan Company Limited', exchange: 'NSE', sector: 'Jewellery' },
  { symbol: 'NESTLEIND.NS', name: 'Nestle India Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'NTPC.NS', name: 'NTPC Limited', exchange: 'NSE', sector: 'Power' },
  { symbol: 'POWERGRID.NS', name: 'Power Grid Corporation', exchange: 'NSE', sector: 'Power' },
  { symbol: 'TATASTEEL.NS', name: 'Tata Steel Limited', exchange: 'NSE', sector: 'Steel' },
  { symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance Limited', exchange: 'NSE', sector: 'NBFC' },
  { symbol: 'HCLTECH.NS', name: 'HCL Technologies Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'WIPRO.NS', name: 'Wipro Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'ONGC.NS', name: 'Oil & Natural Gas Corporation', exchange: 'NSE', sector: 'Oil & Gas' },
  { symbol: 'TECHM.NS', name: 'Tech Mahindra Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'TATAMOTORS.NS', name: 'Tata Motors Limited', exchange: 'NSE', sector: 'Auto' },
  { symbol: 'DRREDDY.NS', name: 'Dr Reddys Laboratories', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'JSWSTEEL.NS', name: 'JSW Steel Limited', exchange: 'NSE', sector: 'Steel' },
  { symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank Limited', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv Limited', exchange: 'NSE', sector: 'Financial Services' },
  { symbol: 'CIPLA.NS', name: 'Cipla Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'COALINDIA.NS', name: 'Coal India Limited', exchange: 'NSE', sector: 'Mining' },
  { symbol: 'DIVISLAB.NS', name: 'Divis Laboratories Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'EICHERMOT.NS', name: 'Eicher Motors Limited', exchange: 'NSE', sector: 'Auto' },
  { symbol: 'GRASIM.NS', name: 'Grasim Industries Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp Limited', exchange: 'NSE', sector: 'Auto' },
  { symbol: 'HINDALCO.NS', name: 'Hindalco Industries Limited', exchange: 'NSE', sector: 'Metals' },
  { symbol: 'BRITANNIA.NS', name: 'Britannia Industries Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'BPCL.NS', name: 'Bharat Petroleum Corporation', exchange: 'NSE', sector: 'Oil & Gas' },
  { symbol: 'SHREECEM.NS', name: 'Shree Cement Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals Enterprise', exchange: 'NSE', sector: 'Healthcare' },

  // Additional popular stocks
  { symbol: 'ADANIPORTS.NS', name: 'Adani Ports and SEZ Limited', exchange: 'NSE', sector: 'Infrastructure' },
  { symbol: 'ADANIENT.NS', name: 'Adani Enterprises Limited', exchange: 'NSE', sector: 'Infrastructure' },
  { symbol: 'GODREJCP.NS', name: 'Godrej Consumer Products', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'PIDILITIND.NS', name: 'Pidilite Industries Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'DABUR.NS', name: 'Dabur India Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'MARICO.NS', name: 'Marico Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'COLPAL.NS', name: 'Colgate Palmolive India', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'BERGEPAINT.NS', name: 'Berger Paints India Limited', exchange: 'NSE', sector: 'Paints' },
  { symbol: 'PAGEIND.NS', name: 'Page Industries Limited', exchange: 'NSE', sector: 'Textiles' },
  { symbol: 'BAJAJ-AUTO.NS', name: 'Bajaj Auto Limited', exchange: 'NSE', sector: 'Auto' },
  { symbol: 'TVSMOTOR.NS', name: 'TVS Motor Company Limited', exchange: 'NSE', sector: 'Auto' },
  { symbol: 'MOTHERSON.NS', name: 'Motherson Sumi Systems', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'BOSCHLTD.NS', name: 'Bosch Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'MINDTREE.NS', name: 'Mindtree Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'MPHASIS.NS', name: 'Mphasis Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'LTI.NS', name: 'L&T Infotech Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'PERSISTENT.NS', name: 'Persistent Systems Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'BIOCON.NS', name: 'Biocon Limited', exchange: 'NSE', sector: 'Biotech' },
  { symbol: 'LUPIN.NS', name: 'Lupin Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'TORNTPHARM.NS', name: 'Torrent Pharmaceuticals', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'AUBANK.NS', name: 'AU Small Finance Bank', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'BANDHANBNK.NS', name: 'Bandhan Bank Limited', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'FEDERALBNK.NS', name: 'Federal Bank Limited', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'PNB.NS', name: 'Punjab National Bank', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'CANBK.NS', name: 'Canara Bank', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'BANKBARODA.NS', name: 'Bank of Baroda', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'IDEA.NS', name: 'Vodafone Idea Limited', exchange: 'NSE', sector: 'Telecom' },
  { symbol: 'SAIL.NS', name: 'Steel Authority of India', exchange: 'NSE', sector: 'Steel' },
  { symbol: 'NMDC.NS', name: 'NMDC Limited', exchange: 'NSE', sector: 'Mining' },
  { symbol: 'VEDL.NS', name: 'Vedanta Limited', exchange: 'NSE', sector: 'Metals' },
  { symbol: 'NATIONALUM.NS', name: 'National Aluminium Company', exchange: 'NSE', sector: 'Metals' },
  { symbol: 'JINDALSTEL.NS', name: 'Jindal Steel & Power', exchange: 'NSE', sector: 'Steel' },
  { symbol: 'ZEEL.NS', name: 'Zee Entertainment Enterprises', exchange: 'NSE', sector: 'Media' },
  { symbol: 'STAR.NS', name: 'Sterlite Technologies', exchange: 'NSE', sector: 'Technology' },
  { symbol: 'IRCTC.NS', name: 'Indian Railway Catering', exchange: 'NSE', sector: 'Services' },
  { symbol: 'NAUKRI.NS', name: 'Info Edge India Limited', exchange: 'NSE', sector: 'Internet' },
  { symbol: 'ZOMATO.NS', name: 'Zomato Limited', exchange: 'NSE', sector: 'Internet' },
  { symbol: 'PAYTM.NS', name: 'One 97 Communications Limited', exchange: 'NSE', sector: 'Fintech' },

  // Additional Nifty Next 50 stocks
  { symbol: 'ABB.NS', name: 'ABB India Limited', exchange: 'NSE', sector: 'Industrial Equipment' },
  { symbol: 'ACC.NS', name: 'ACC Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'ADANIGREEN.NS', name: 'Adani Green Energy Limited', exchange: 'NSE', sector: 'Renewable Energy' },
  { symbol: 'ADANITRANS.NS', name: 'Adani Transmission Limited', exchange: 'NSE', sector: 'Power' },
  { symbol: 'AMBUJACEM.NS', name: 'Ambuja Cements Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'ASHOKLEY.NS', name: 'Ashok Leyland Limited', exchange: 'NSE', sector: 'Auto' },
  { symbol: 'ATGL.NS', name: 'Adani Total Gas Limited', exchange: 'NSE', sector: 'Oil & Gas' },
  { symbol: 'ASTRAL.NS', name: 'Astral Limited', exchange: 'NSE', sector: 'Plastics' },
  { symbol: 'AUROPHARMA.NS', name: 'Aurobindo Pharma Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'BAJAJHLDNG.NS', name: 'Bajaj Holdings & Investment Limited', exchange: 'NSE', sector: 'Financial Services' },
  { symbol: 'BALKRISIND.NS', name: 'Balkrishna Industries Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'BHARATFORG.NS', name: 'Bharat Forge Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'BOSCHLTD.NS', name: 'Bosch Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'CHOLAFIN.NS', name: 'Cholamandalam Investment and Finance Company Limited', exchange: 'NSE', sector: 'NBFC' },
  { symbol: 'COLPAL.NS', name: 'Colgate Palmolive (India) Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'CONCOR.NS', name: 'Container Corporation of India Limited', exchange: 'NSE', sector: 'Logistics' },
  { symbol: 'CUMMINSIND.NS', name: 'Cummins India Limited', exchange: 'NSE', sector: 'Industrial Equipment' },
  { symbol: 'DLF.NS', name: 'DLF Limited', exchange: 'NSE', sector: 'Real Estate' },
  { symbol: 'DABUR.NS', name: 'Dabur India Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'GAIL.NS', name: 'GAIL (India) Limited', exchange: 'NSE', sector: 'Oil & Gas' },
  { symbol: 'GLAND.NS', name: 'Gland Pharma Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'GODREJPROP.NS', name: 'Godrej Properties Limited', exchange: 'NSE', sector: 'Real Estate' },
  { symbol: 'HINDPETRO.NS', name: 'Hindustan Petroleum Corporation Limited', exchange: 'NSE', sector: 'Oil & Gas' },
  { symbol: 'ICICIPRULI.NS', name: 'ICICI Prudential Life Insurance Company Limited', exchange: 'NSE', sector: 'Insurance' },
  { symbol: 'IGL.NS', name: 'Indraprastha Gas Limited', exchange: 'NSE', sector: 'Oil & Gas' },
  { symbol: 'INDUSTOWER.NS', name: 'Indus Towers Limited', exchange: 'NSE', sector: 'Telecom Infrastructure' },
  { symbol: 'JUBLFOOD.NS', name: 'Jubilant FoodWorks Limited', exchange: 'NSE', sector: 'Food Services' },
  { symbol: 'LICHSGFIN.NS', name: 'LIC Housing Finance Limited', exchange: 'NSE', sector: 'Housing Finance' },
  { symbol: 'LTI.NS', name: 'Larsen & Toubro Infotech Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'LUPIN.NS', name: 'Lupin Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'MANAPPURAM.NS', name: 'Manappuram Finance Limited', exchange: 'NSE', sector: 'NBFC' },
  { symbol: 'MARICO.NS', name: 'Marico Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'MFSL.NS', name: 'Max Financial Services Limited', exchange: 'NSE', sector: 'Insurance' },
  { symbol: 'MPHASIS.NS', name: 'Mphasis Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'MRF.NS', name: 'MRF Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'MUTHOOTFIN.NS', name: 'Muthoot Finance Limited', exchange: 'NSE', sector: 'NBFC' },
  { symbol: 'NAM-INDIA.NS', name: 'Nippon Life India Asset Management Limited', exchange: 'NSE', sector: 'Asset Management' },
  { symbol: 'NAVINFLUOR.NS', name: 'Navin Fluorine International Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'NYKAA.NS', name: 'FSN E-Commerce Ventures Limited (Nykaa)', exchange: 'NSE', sector: 'E-commerce' },
  { symbol: 'OFSS.NS', name: 'Oracle Financial Services Software Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'PETRONET.NS', name: 'Petronet LNG Limited', exchange: 'NSE', sector: 'Oil & Gas' },
  { symbol: 'PIIND.NS', name: 'PI Industries Limited', exchange: 'NSE', sector: 'Agro Chemicals' },
  { symbol: 'PEL.NS', name: 'Piramal Enterprises Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'SAIL.NS', name: 'Steel Authority of India Limited', exchange: 'NSE', sector: 'Steel' },
  { symbol: 'SRF.NS', name: 'SRF Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'SIEMENS.NS', name: 'Siemens Limited', exchange: 'NSE', sector: 'Industrial Equipment' },
  { symbol: 'SUZLON.NS', name: 'Suzlon Energy Limited', exchange: 'NSE', sector: 'Renewable Energy' },
  { symbol: 'TORNTPHARM.NS', name: 'Torrent Pharmaceuticals Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'TRENT.NS', name: 'Trent Limited', exchange: 'NSE', sector: 'Retail' },
  { symbol: 'UBL.NS', name: 'United Breweries Limited', exchange: 'NSE', sector: 'Beverages' },
  { symbol: 'VOLTAS.NS', name: 'Voltas Limited', exchange: 'NSE', sector: 'Consumer Durables' },
  { symbol: 'WHIRLPOOL.NS', name: 'Whirlpool of India Limited', exchange: 'NSE', sector: 'Consumer Durables' },
  { symbol: 'ZYDUSLIFE.NS', name: 'Zydus Lifesciences Limited', exchange: 'NSE', sector: 'Pharma' },

  // Mid-cap stocks
  { symbol: 'ALKEM.NS', name: 'Alkem Laboratories Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'APOLLOTYRE.NS', name: 'Apollo Tyres Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'BATAINDIA.NS', name: 'Bata India Limited', exchange: 'NSE', sector: 'Footwear' },
  { symbol: 'BHARATRAS.NS', name: 'Bharat Rasayan Limited', exchange: 'NSE', sector: 'Agro Chemicals' },
  { symbol: 'BLUEDART.NS', name: 'Blue Dart Express Limited', exchange: 'NSE', sector: 'Logistics' },
  { symbol: 'CASTROLIND.NS', name: 'Castrol India Limited', exchange: 'NSE', sector: 'Lubricants' },
  { symbol: 'CROMPTON.NS', name: 'Crompton Greaves Consumer Electricals Limited', exchange: 'NSE', sector: 'Consumer Durables' },
  { symbol: 'ESCORTS.NS', name: 'Escorts Kubota Limited', exchange: 'NSE', sector: 'Auto' },
  { symbol: 'EXIDEIND.NS', name: 'Exide Industries Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'FORTIS.NS', name: 'Fortis Healthcare Limited', exchange: 'NSE', sector: 'Healthcare' },
  { symbol: 'GLAXO.NS', name: 'GlaxoSmithKline Pharmaceuticals Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'GODREJIND.NS', name: 'Godrej Industries Limited', exchange: 'NSE', sector: 'Conglomerate' },
  { symbol: 'HATSUN.NS', name: 'Hatsun Agro Product Limited', exchange: 'NSE', sector: 'Dairy' },
  { symbol: 'HAVELLS.NS', name: 'Havells India Limited', exchange: 'NSE', sector: 'Consumer Durables' },
  { symbol: 'IIFL.NS', name: 'IIFL Finance Limited', exchange: 'NSE', sector: 'NBFC' },
  { symbol: 'IPCALAB.NS', name: 'Ipca Laboratories Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'JKCEMENT.NS', name: 'JK Cement Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'JUBLINGREA.NS', name: 'Jubilant Ingrevia Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'KAJARIACER.NS', name: 'Kajaria Ceramics Limited', exchange: 'NSE', sector: 'Ceramics' },
  { symbol: 'KANSAINER.NS', name: 'Kansai Nerolac Paints Limited', exchange: 'NSE', sector: 'Paints' },
  { symbol: 'LAURUSLABS.NS', name: 'Laurus Labs Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'LINDEINDIA.NS', name: 'Linde India Limited', exchange: 'NSE', sector: 'Industrial Gases' },
  { symbol: 'MAHABANK.NS', name: 'Bank of Maharashtra', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'MANKIND.NS', name: 'Mankind Pharma Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'METROBRAND.NS', name: 'Metro Brands Limited', exchange: 'NSE', sector: 'Footwear' },
  { symbol: 'NATCOPHARM.NS', name: 'Natco Pharma Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'OBEROIRLTY.NS', name: 'Oberoi Realty Limited', exchange: 'NSE', sector: 'Real Estate' },
  { symbol: 'PATANJALI.NS', name: 'Patanjali Foods Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'POLYCAB.NS', name: 'Polycab India Limited', exchange: 'NSE', sector: 'Electricals' },
  { symbol: 'PRESTIGE.NS', name: 'Prestige Estates Projects Limited', exchange: 'NSE', sector: 'Real Estate' },
  { symbol: 'RAMCOCEM.NS', name: 'The Ramco Cements Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'SANOFI.NS', name: 'Sanofi India Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'SCHAEFFLER.NS', name: 'Schaeffler India Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'SONACOMS.NS', name: 'Sona BLW Precision Forgings Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'SUPREMEIND.NS', name: 'Supreme Industries Limited', exchange: 'NSE', sector: 'Plastics' },
  { symbol: 'SYNGENE.NS', name: 'Syngene International Limited', exchange: 'NSE', sector: 'Biotech' },
  { symbol: 'TATACOMM.NS', name: 'Tata Communications Limited', exchange: 'NSE', sector: 'Telecom' },
  { symbol: 'TATACONSUM.NS', name: 'Tata Consumer Products Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'TATAELXSI.NS', name: 'Tata Elxsi Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'TATAPOWER.NS', name: 'Tata Power Company Limited', exchange: 'NSE', sector: 'Power' },
  { symbol: 'TV18BRDCST.NS', name: 'TV18 Broadcast Limited', exchange: 'NSE', sector: 'Media' },
  { symbol: 'UCOBANK.NS', name: 'UCO Bank', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'UNIONBANK.NS', name: 'Union Bank of India', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'VBL.NS', name: 'Varun Beverages Limited', exchange: 'NSE', sector: 'Beverages' },
  { symbol: 'VINATIORGA.NS', name: 'Vinati Organics Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'WABCOINDIA.NS', name: 'WABCO India Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'YESBANK.NS', name: 'Yes Bank Limited', exchange: 'NSE', sector: 'Banking' },

  // Small-cap stocks
  { symbol: 'AARTIDRUGS.NS', name: 'Aarti Drugs Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'AARTIIND.NS', name: 'Aarti Industries Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'ABCAPITAL.NS', name: 'Aditya Birla Capital Limited', exchange: 'NSE', sector: 'Financial Services' },
  { symbol: 'ABFRL.NS', name: 'Aditya Birla Fashion and Retail Limited', exchange: 'NSE', sector: 'Retail' },
  { symbol: 'ADVENZYMES.NS', name: 'Advanced Enzyme Technologies Limited', exchange: 'NSE', sector: 'Biotech' },
  { symbol: 'AEGISCHEM.NS', name: 'Aegis Logistics Limited', exchange: 'NSE', sector: 'Oil & Gas' },
  { symbol: 'AFFLE.NS', name: 'Affle (India) Limited', exchange: 'NSE', sector: 'Advertising' },
  { symbol: 'AJANTPHARM.NS', name: 'Ajanta Pharma Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'ALKYLAMINE.NS', name: 'Alkyl Amines Chemicals Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'AMARAJABAT.NS', name: 'Amara Raja Batteries Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'ANURAS.NS', name: 'Anupam Rasayan India Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'APTUS.NS', name: 'Aptus Value Housing Finance India Limited', exchange: 'NSE', sector: 'Housing Finance' },
  { symbol: 'ASAHIINDIA.NS', name: 'Asahi India Glass Limited', exchange: 'NSE', sector: 'Glass' },
  { symbol: 'ASTERDM.NS', name: 'Aster DM Healthcare Limited', exchange: 'NSE', sector: 'Healthcare' },
  { symbol: 'ASTRAZEN.NS', name: 'AstraZeneca Pharma India Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'ATUL.NS', name: 'Atul Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'AUBANK.NS', name: 'AU Small Finance Bank Limited', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'AVANTIFEED.NS', name: 'Avanti Feeds Limited', exchange: 'NSE', sector: 'Aquaculture' },
  { symbol: 'BAJAJELEC.NS', name: 'Bajaj Electricals Limited', exchange: 'NSE', sector: 'Consumer Durables' },
  { symbol: 'BALAMINES.NS', name: 'Balaji Amines Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'BALRAMCHIN.NS', name: 'Balrampur Chini Mills Limited', exchange: 'NSE', sector: 'Sugar' },
  { symbol: 'BECTORFOOD.NS', name: 'Mrs. Bectors Food Specialities Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'BEL.NS', name: 'Bharat Electronics Limited', exchange: 'NSE', sector: 'Defense' },
  { symbol: 'BEML.NS', name: 'BEML Limited', exchange: 'NSE', sector: 'Industrial Equipment' },
  { symbol: 'BIRLACORPN.NS', name: 'Birla Corporation Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'BLUESTARCO.NS', name: 'Blue Star Limited', exchange: 'NSE', sector: 'Consumer Durables' },
  { symbol: 'BORORENEW.NS', name: 'Borosil Renewables Limited', exchange: 'NSE', sector: 'Renewable Energy' },
  { symbol: 'BRIGADE.NS', name: 'Brigade Enterprises Limited', exchange: 'NSE', sector: 'Real Estate' },
  { symbol: 'BSOFT.NS', name: 'Birlasoft Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'CAMS.NS', name: 'Computer Age Management Services Limited', exchange: 'NSE', sector: 'Financial Services' },
  { symbol: 'CARBORUNIV.NS', name: 'Carborundum Universal Limited', exchange: 'NSE', sector: 'Abrasives' },
  { symbol: 'CENTRALBK.NS', name: 'Central Bank of India', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'CENTURYPLY.NS', name: 'Century Plyboards (India) Limited', exchange: 'NSE', sector: 'Building Materials' },
  { symbol: 'CHEMPLAST.NS', name: 'Chemplast Sanmar Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'CHOLAHLDNG.NS', name: 'Cholamandalam Financial Holdings Limited', exchange: 'NSE', sector: 'Financial Services' },
  { symbol: 'CLEAN.NS', name: 'Clean Science and Technology Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'COFORGE.NS', name: 'Coforge Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'COROMANDEL.NS', name: 'Coromandel International Limited', exchange: 'NSE', sector: 'Fertilizers' },
  { symbol: 'CYIENT.NS', name: 'Cyient Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'DALBHARAT.NS', name: 'Dalmia Bharat Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'DATAPATTNS.NS', name: 'Data Patterns (India) Limited', exchange: 'NSE', sector: 'Defense' },
  { symbol: 'DCBBANK.NS', name: 'DCB Bank Limited', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'DEEPAKNTR.NS', name: 'Deepak Nitrite Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'DELTACORP.NS', name: 'Delta Corp Limited', exchange: 'NSE', sector: 'Gaming' },
  { symbol: 'DEVYANI.NS', name: 'Devyani International Limited', exchange: 'NSE', sector: 'Food Services' },
  { symbol: 'DIXON.NS', name: 'Dixon Technologies (India) Limited', exchange: 'NSE', sector: 'Electronics' },
  { symbol: 'EIHOTEL.NS', name: 'EIH Limited', exchange: 'NSE', sector: 'Hotels' },
  { symbol: 'ELGIEQUIP.NS', name: 'Elgi Equipments Limited', exchange: 'NSE', sector: 'Industrial Equipment' },
  { symbol: 'ENDURANCE.NS', name: 'Endurance Technologies Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'EQUITASBNK.NS', name: 'Equitas Small Finance Bank Limited', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'ERIS.NS', name: 'Eris Lifesciences Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'ESABINDIA.NS', name: 'ESAB India Limited', exchange: 'NSE', sector: 'Industrial Equipment' },
  { symbol: 'FACT.NS', name: 'Fertilizers and Chemicals Travancore Limited', exchange: 'NSE', sector: 'Fertilizers' },
  { symbol: 'FINCABLES.NS', name: 'Finolex Cables Limited', exchange: 'NSE', sector: 'Cables' },
  { symbol: 'FIVESTAR.NS', name: 'Five-Star Business Finance Limited', exchange: 'NSE', sector: 'NBFC' },
  { symbol: 'FLUOROCHEM.NS', name: 'Gujarat Fluorochemicals Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'FSNE.NS', name: 'FSN E-Commerce Ventures Limited (Nykaa)', exchange: 'NSE', sector: 'E-commerce' },
  { symbol: 'GMMPFAUDLR.NS', name: 'GMM Pfaudler Limited', exchange: 'NSE', sector: 'Industrial Equipment' },
  { symbol: 'GNFC.NS', name: 'Gujarat Narmada Valley Fertilizers & Chemicals Limited', exchange: 'NSE', sector: 'Fertilizers' },
  { symbol: 'GPIL.NS', name: 'Godawari Power & Ispat Limited', exchange: 'NSE', sector: 'Steel' },
  { symbol: 'GRANULES.NS', name: 'Granules India Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'GRAPHITE.NS', name: 'Graphite India Limited', exchange: 'NSE', sector: 'Carbon' },
  { symbol: 'GREENPANEL.NS', name: 'Greenpanel Industries Limited', exchange: 'NSE', sector: 'Building Materials' },
  { symbol: 'GSPL.NS', name: 'Gujarat State Petronet Limited', exchange: 'NSE', sector: 'Oil & Gas' },
  { symbol: 'HAPPSTMNDS.NS', name: 'Happiest Minds Technologies Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'HATHWAY.NS', name: 'Hathway Cable & Datacom Limited', exchange: 'NSE', sector: 'Media' },
  { symbol: 'HEG.NS', name: 'HEG Limited', exchange: 'NSE', sector: 'Carbon' },
  { symbol: 'HEIDELBERG.NS', name: 'HeidelbergCement India Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'HFCL.NS', name: 'HFCL Limited', exchange: 'NSE', sector: 'Telecom Equipment' },
  { symbol: 'HONAUT.NS', name: 'Honeywell Automation India Limited', exchange: 'NSE', sector: 'Industrial Automation' },
  { symbol: 'HUDCO.NS', name: 'Housing & Urban Development Corporation Limited', exchange: 'NSE', sector: 'Housing Finance' },
  { symbol: 'IBULHSGFIN.NS', name: 'Indiabulls Housing Finance Limited', exchange: 'NSE', sector: 'Housing Finance' },
  { symbol: 'ICICIGI.NS', name: 'ICICI Lombard General Insurance Company Limited', exchange: 'NSE', sector: 'Insurance' },
  { symbol: 'ICRA.NS', name: 'ICRA Limited', exchange: 'NSE', sector: 'Financial Services' },
  { symbol: 'IDBI.NS', name: 'IDBI Bank Limited', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'IDFC.NS', name: 'IDFC Limited', exchange: 'NSE', sector: 'Financial Services' },
  { symbol: 'IEX.NS', name: 'Indian Energy Exchange Limited', exchange: 'NSE', sector: 'Power' },
  { symbol: 'IFBIND.NS', name: 'IFB Industries Limited', exchange: 'NSE', sector: 'Consumer Durables' },
  { symbol: 'IGL.NS', name: 'Indraprastha Gas Limited', exchange: 'NSE', sector: 'Oil & Gas' },
  { symbol: 'INDIACEM.NS', name: 'The India Cements Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'INDIAMART.NS', name: 'Indiamart Intermesh Limited', exchange: 'NSE', sector: 'Internet' },
  { symbol: 'INDIANB.NS', name: 'Indian Bank', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'INDIGO.NS', name: 'InterGlobe Aviation Limited', exchange: 'NSE', sector: 'Aviation' },
  { symbol: 'INDIGOPNTS.NS', name: 'Indigo Paints Limited', exchange: 'NSE', sector: 'Paints' },
  { symbol: 'INDOSTAR.NS', name: 'IndoStar Capital Finance Limited', exchange: 'NSE', sector: 'NBFC' },
  { symbol: 'INDUSTOWER.NS', name: 'Indus Towers Limited', exchange: 'NSE', sector: 'Telecom Infrastructure' },
  { symbol: 'INFIBEAM.NS', name: 'Infibeam Avenues Limited', exchange: 'NSE', sector: 'E-commerce' },
  { symbol: 'INOXLEISUR.NS', name: 'INOX Leisure Limited', exchange: 'NSE', sector: 'Entertainment' },
  { symbol: 'IOB.NS', name: 'Indian Overseas Bank', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'IPCALAB.NS', name: 'Ipca Laboratories Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'IRB.NS', name: 'IRB Infrastructure Developers Limited', exchange: 'NSE', sector: 'Infrastructure' },
  { symbol: 'ISEC.NS', name: 'ICICI Securities Limited', exchange: 'NSE', sector: 'Financial Services' },
  { symbol: 'ITI.NS', name: 'ITI Limited', exchange: 'NSE', sector: 'Telecom Equipment' },
  { symbol: 'JBCHEPHARM.NS', name: 'JB Chemicals & Pharmaceuticals Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'JINDALSAW.NS', name: 'Jindal Saw Limited', exchange: 'NSE', sector: 'Steel' },
  { symbol: 'JKLAKSHMI.NS', name: 'JK Lakshmi Cement Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'JKPAPER.NS', name: 'JK Paper Limited', exchange: 'NSE', sector: 'Paper' },
  { symbol: 'JMFINANCIL.NS', name: 'JM Financial Limited', exchange: 'NSE', sector: 'Financial Services' },
  { symbol: 'JSL.NS', name: 'Jindal Stainless Limited', exchange: 'NSE', sector: 'Steel' },
  { symbol: 'JSWENERGY.NS', name: 'JSW Energy Limited', exchange: 'NSE', sector: 'Power' },
  { symbol: 'JTEKTINDIA.NS', name: 'JTEKT India Limited', exchange: 'NSE', sector: 'Auto Components' },
  { symbol: 'JUBLPHARMA.NS', name: 'Jubilant Pharmova Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'JUSTDIAL.NS', name: 'Just Dial Limited', exchange: 'NSE', sector: 'Internet' },
  { symbol: 'JWL.NS', name: 'Jupiter Wagons Limited', exchange: 'NSE', sector: 'Railway Equipment' },
  { symbol: 'KALYANKJIL.NS', name: 'Kalyan Jewellers India Limited', exchange: 'NSE', sector: 'Jewellery' },
  { symbol: 'KARURVYSYA.NS', name: 'Karur Vysya Bank Limited', exchange: 'NSE', sector: 'Banking' },
  { symbol: 'KAYNES.NS', name: 'Kaynes Technology India Limited', exchange: 'NSE', sector: 'Electronics' },
  { symbol: 'KEI.NS', name: 'KEI Industries Limited', exchange: 'NSE', sector: 'Cables' },
  { symbol: 'KIMS.NS', name: 'Krishna Institute of Medical Sciences Limited', exchange: 'NSE', sector: 'Healthcare' },
  { symbol: 'KNRCON.NS', name: 'KNR Constructions Limited', exchange: 'NSE', sector: 'Infrastructure' },
  { symbol: 'KPITTECH.NS', name: 'KPIT Technologies Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'KRBL.NS', name: 'KRBL Limited', exchange: 'NSE', sector: 'FMCG' },
  { symbol: 'KSB.NS', name: 'KSB Limited', exchange: 'NSE', sector: 'Industrial Equipment' },
  { symbol: 'LAOPALA.NS', name: 'La Opala RG Limited', exchange: 'NSE', sector: 'Consumer Goods' },
  { symbol: 'LATENTVIEW.NS', name: 'Latent View Analytics Limited', exchange: 'NSE', sector: 'Analytics' },
  { symbol: 'LEMONTREE.NS', name: 'Lemon Tree Hotels Limited', exchange: 'NSE', sector: 'Hotels' },
  { symbol: 'LINDEINDIA.NS', name: 'Linde India Limited', exchange: 'NSE', sector: 'Industrial Gases' },
  { symbol: 'LUXIND.NS', name: 'Lux Industries Limited', exchange: 'NSE', sector: 'Textiles' },
  { symbol: 'MGL.NS', name: 'Mahanagar Gas Limited', exchange: 'NSE', sector: 'Oil & Gas' },
  { symbol: 'MHRIL.NS', name: 'Mahindra Holidays & Resorts India Limited', exchange: 'NSE', sector: 'Hospitality' },
  { symbol: 'MOTILALOFS.NS', name: 'Motilal Oswal Financial Services Limited', exchange: 'NSE', sector: 'Financial Services' },
  { symbol: 'MPHASIS.NS', name: 'Mphasis Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'NATCOPHARM.NS', name: 'Natco Pharma Limited', exchange: 'NSE', sector: 'Pharma' },
  { symbol: 'NAVA.NS', name: 'Nava Bharat Ventures Limited', exchange: 'NSE', sector: 'Metals' },
  { symbol: 'NAVINFLUOR.NS', name: 'Navin Fluorine International Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'NBCC.NS', name: 'NBCC (India) Limited', exchange: 'NSE', sector: 'Construction' },
  { symbol: 'NCC.NS', name: 'NCC Limited', exchange: 'NSE', sector: 'Construction' },
  { symbol: 'NESCO.NS', name: 'Nesco Limited', exchange: 'NSE', sector: 'Infrastructure' },
  { symbol: 'NHPC.NS', name: 'NHPC Limited', exchange: 'NSE', sector: 'Power' },
  { symbol: 'NIACL.NS', name: 'The New India Assurance Company Limited', exchange: 'NSE', sector: 'Insurance' },
  { symbol: 'NIITLTD.NS', name: 'NIIT Limited', exchange: 'NSE', sector: 'Education' },
  { symbol: 'NLCINDIA.NS', name: 'NLC India Limited', exchange: 'NSE', sector: 'Power' },
  { symbol: 'NOCIL.NS', name: 'NOCIL Limited', exchange: 'NSE', sector: 'Chemicals' },
  { symbol: 'NUVOCO.NS', name: 'Nuvoco Vistas Corporation Limited', exchange: 'NSE', sector: 'Cement' },
  { symbol: 'OBEROIRLTY.NS', name: 'Oberoi Realty Limited', exchange: 'NSE', sector: 'Real Estate' },
  { symbol: 'ORIENTELEC.NS', name: 'Orient Electric Limited', exchange: 'NSE', sector: 'Consumer Durables' },
  { symbol: 'PAGEIND.NS', name: 'Page Industries Limited', exchange: 'NSE', sector: 'Textiles' },
  { symbol: 'PERSISTENT.NS', name: 'Persistent Systems Limited', exchange: 'NSE', sector: 'IT' },
  { symbol: 'PFIZER.NS', name: 'Pfizer Limited', exchange: 'NSE', sector: 'Pharma' },
];

export const searchStocks = (query: string, limit: number = 10): StockInfo[] => {
  if (!query.trim()) {
    return indianStocks.slice(0, limit);
  }

  const searchTerm = query.toLowerCase().trim();

  // Search by symbol, name, and sector
  const filtered = indianStocks.filter(stock => {
    const symbolMatch = stock.symbol.toLowerCase().includes(searchTerm);
    const nameMatch = stock.name.toLowerCase().includes(searchTerm);
    const sectorMatch = stock.sector?.toLowerCase().includes(searchTerm);

    return symbolMatch || nameMatch || sectorMatch;
  });

  // Sort by relevance - exact symbol matches first, then name matches
  return filtered.sort((a, b) => {
    const aSymbolExact = a.symbol.toLowerCase().startsWith(searchTerm);
    const bSymbolExact = b.symbol.toLowerCase().startsWith(searchTerm);

    if (aSymbolExact && !bSymbolExact) return -1;
    if (!aSymbolExact && bSymbolExact) return 1;

    const aNameExact = a.name.toLowerCase().startsWith(searchTerm);
    const bNameExact = b.name.toLowerCase().startsWith(searchTerm);

    if (aNameExact && !bNameExact) return -1;
    if (!aNameExact && bNameExact) return 1;

    return a.name.localeCompare(b.name);
  }).slice(0, limit);
};

export const getPopularStocks = (): StockInfo[] => {
  return indianStocks.slice(0, 15);
};

export const getStocksByCategory = (category: string): StockInfo[] => {
  return indianStocks.filter(stock =>
    stock.sector?.toLowerCase() === category.toLowerCase()
  );
};
