// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// The showcase must stay usable even when no Supabase project is configured
// (missing env must never crash the bundle; the original backend was owned by
// the prototyping tool and can disappear). When env is absent, every call
// resolves to a "not configured" failure so data layers fall through to their
// clearly labeled simulated sources.
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const notConfiguredError = () =>
  new Error('Supabase is not configured (missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY). Running in fallback mode.');

// A client stand-in that never throws: any namespace/method chain resolves to
// { data: null, error }, so callers degrade into their fallback paths.
function createUnavailableClient(): SupabaseClient<Database> {
  const failedResult = () => ({ data: null, error: notConfiguredError() });

  // Chainable + thenable stand-in: supabase.from('x').select() etc. all
  // resolve to a failed result instead of raising.
  const chainable: unknown = new Proxy(function () {}, {
    get(_target, prop) {
      if (prop === 'then') {
        return (resolve: (value: unknown) => unknown) => resolve(failedResult());
      }
      return chainable;
    },
    apply() {
      return chainable;
    },
  });

  const base: Record<string, unknown> = {
    functions: {
      invoke: async () => failedResult(),
    },
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: notConfiguredError() }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => undefined } } }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error: notConfiguredError() }),
      signUp: async () => ({ data: { user: null, session: null }, error: notConfiguredError() }),
      signOut: async () => ({ error: null }),
    },
  };

  return new Proxy(base, {
    get(target, prop) {
      if (prop in target) return target[prop as string];
      return chainable;
    },
  }) as unknown as SupabaseClient<Database>;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: SupabaseClient<Database> = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL as string, SUPABASE_PUBLISHABLE_KEY as string, {
      auth: {
        storage: brokeredPreviewStorage(),
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createUnavailableClient();

if (!isSupabaseConfigured) {
  console.warn('[StockSense] Supabase env not configured; running with labeled fallback data.');
}
